/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class tc_table {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public tc_table(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(tc_table obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinkercellJNI.delete_tc_table(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRows(int value) {
    tinkercellJNI.tc_table_rows_set(swigCPtr, this, value);
  }

  public int getRows() {
    return tinkercellJNI.tc_table_rows_get(swigCPtr, this);
  }

  public void setCols(int value) {
    tinkercellJNI.tc_table_cols_set(swigCPtr, this, value);
  }

  public int getCols() {
    return tinkercellJNI.tc_table_cols_get(swigCPtr, this);
  }

  public void setStrings(SWIGTYPE_p_p_char value) {
    tinkercellJNI.tc_table_strings_set(swigCPtr, this, SWIGTYPE_p_p_char.getCPtr(value));
  }

  public SWIGTYPE_p_p_char getStrings() {
    long cPtr = tinkercellJNI.tc_table_strings_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_p_char(cPtr, false);
  }

  public void setRownames(tc_strings value) {
    tinkercellJNI.tc_table_rownames_set(swigCPtr, this, tc_strings.getCPtr(value), value);
  }

  public tc_strings getRownames() {
    long cPtr = tinkercellJNI.tc_table_rownames_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tc_strings(cPtr, false);
  }

  public void setColnames(tc_strings value) {
    tinkercellJNI.tc_table_colnames_set(swigCPtr, this, tc_strings.getCPtr(value), value);
  }

  public tc_strings getColnames() {
    long cPtr = tinkercellJNI.tc_table_colnames_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tc_strings(cPtr, false);
  }

  public tc_table() {
    this(tinkercellJNI.new_tc_table(), true);
  }

}
