/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class tc_matrix {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected tc_matrix(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(tc_matrix obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        tinkercellJNI.delete_tc_matrix(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRows(int value) {
    tinkercellJNI.tc_matrix_rows_set(swigCPtr, this, value);
  }

  public int getRows() {
    return tinkercellJNI.tc_matrix_rows_get(swigCPtr, this);
  }

  public void setCols(int value) {
    tinkercellJNI.tc_matrix_cols_set(swigCPtr, this, value);
  }

  public int getCols() {
    return tinkercellJNI.tc_matrix_cols_get(swigCPtr, this);
  }

  public void setValues(SWIGTYPE_p_double value) {
    tinkercellJNI.tc_matrix_values_set(swigCPtr, this, SWIGTYPE_p_double.getCPtr(value));
  }

  public SWIGTYPE_p_double getValues() {
    long cPtr = tinkercellJNI.tc_matrix_values_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_double(cPtr, false);
  }

  public void setRownames(tc_strings value) {
    tinkercellJNI.tc_matrix_rownames_set(swigCPtr, this, tc_strings.getCPtr(value), value);
  }

  public tc_strings getRownames() {
    long cPtr = tinkercellJNI.tc_matrix_rownames_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tc_strings(cPtr, false);
  }

  public void setColnames(tc_strings value) {
    tinkercellJNI.tc_matrix_colnames_set(swigCPtr, this, tc_strings.getCPtr(value), value);
  }

  public tc_strings getColnames() {
    long cPtr = tinkercellJNI.tc_matrix_colnames_get(swigCPtr, this);
    return (cPtr == 0) ? null : new tc_strings(cPtr, false);
  }

  public tc_matrix() {
    this(tinkercellJNI.new_tc_matrix(), true);
  }

}
