#---------------------------------------------------------------------------
# CMAKE Install files
#---------------------------------------------------------------------------

FILE(GLOB TINKERCELL_ALL_FILES_IN_BIN 
	${TINKERCELL_BINARY_BIN_DIR}/*.DLL 
	${TINKERCELL_BINARY_BIN_DIR}/*.dll
	${TINKERCELL_BINARY_BIN_DIR}/*.so
	${TINKERCELL_BINARY_BIN_DIR}/*.SO
	${TINKERCELL_BINARY_BIN_DIR}/*.dylib
	${TINKERCELL_BINARY_BIN_DIR}/*.DYLIB
	${TINKERCELL_BINARY_BIN_DIR}/*.a
	${TINKERCELL_BINARY_BIN_DIR}/*.lib
	${TINKERCELL_BINARY_BIN_DIR}/*.txt
	${TINKERCELL_BINARY_BIN_DIR}/*.TXT
	${TINKERCELL_BINARY_BIN_DIR}/*.zip
	${TINKERCELL_BINARY_BIN_DIR}/*.py)
INSTALL(FILES ${TINKERCELL_ALL_FILES_IN_BIN}
  DESTINATION bin/../
)

# ---------------------
# CPACK
# --------------------

SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "CAD For Synthetic Biology")

IF (UNIX AND NOT APPLE)
   SET(CPACK_PACKAGE_CONTACT "admin@tinkercell.com")
   SET(CPACK_DEBIAN_PACKAGE_SECTION "Science")
   SET(CPACK_DEBIAN_PACKAGE_DESCRIPTION "CAD For Synthetic Biology")
ENDIF (UNIX AND NOT APPLE)

INCLUDE(InstallRequiredSystemLibraries)

SET(CPACK_PACKAGE_FILE_NAME "TinkerCell")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "TinkerCell")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "TinkerCell")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "TinkerCell Installer")
SET(CPACK_PACKAGE_VENDOR "Deepak Chandran")
SET(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/COPYRIGHT.TXT")
SET(CPACK_PACKAGE_VERSION_MAJOR ${TINKERCELL_MAJOR_VERSION})
SET(CPACK_PACKAGE_VERSION_MINOR ${TINKERCELL_MINOR_VERSION})
IF(WIN32 AND NOT UNIX)
  #SET(CPACK_CMAKE_GENERATOR NSIS)
  # There is a bug in NSI that does not handle full unix paths properly. Make
  # sure there is at least one set of four (4) backlasshes.
  SET(CPACK_NSIS_MUI_ICON "${TINKERCELL_SOURCE_DIR}/Main\\\\tinkercell.ico")
  SET(CPACK_PACKAGE_ICON "${TINKERCELL_SOURCE_DIR}/Main\\\\images\\\\tinkercell.png")
  SET(CPACK_NSIS_INSTALLED_ICON_NAME "bin\\\\TinkerCellSetup.exe")
  SET(CPACK_NSIS_DISPLAY_NAME "${TINKERCELL_INSTALL_DIRECTORY} TinkerCell")
  SET(CPACK_NSIS_HELP_LINK "http:\\\\\\\\www.tinkercell.com")
  SET(CPACK_NSIS_URL_INFO_ABOUT "http:\\\\\\\\www.tinkercell.com")
  SET(CPACK_NSIS_CONTACT "admin@tinkercell.com")
  SET(CPACK_NSIS_MODIFY_PATH ON)
  OPTION(CPACK_BINARY_NSIS OFF)
  OPTION(CPACK_SOURCE_ZIP OFF)
  OPTION(CPACK_BINARY_ZIP ON)
ENDIF(WIN32 AND NOT UNIX)

IF(UNIX AND NOT APPLE)
	OPTION(CPACK_BINARY_TGZ ON)
ENDIF(UNIX AND NOT APPLE)

SET(CPACK_PACKAGE_EXECUTABLES "TinkerCell" "TinkerCell")
SET(CPACK_PACKAGE_EXECUTABLES "NodeGraphics" "NodeGraphics")

INCLUDE(CPack)

